### ISSUE TITLE
Missing separator error

### ISSUE THREAD

**Issue by setfires** [mojadita/slowtty#2] opened 2019-09-30 21:29 UTC
When I attempt to make I receive:

`Makefile:40: *** missing separator.  Stop.`

I reverted to an older Makefile and I get

```
slowtty.c:19:10: fatal error: libutil.h: No such file or directory
 #include <libutil.h>
          ^~~~~~~~~~~
```

**Comment by mojadita** [comment] 2019-10-02 03:34
Well, that error is due to using GNU Make instead of BSD bmake.  You have
two options: tweak the Makefile to unroll the .for loop, or install bmake
and build the application with bmake.

I'll patch the Makefile to do it for you, but when I have some time (most
probably this week) I'll try to write it to work with both bmake and gmake.

I wrote this program in Linux, but as I changed my desktop to FreeBSD I
rewrote it to use BSD Makefile format, and more reliable signals.  This is
the reason of the two errors you found on it.

**Comment by mojadita** [comment] 2019-10-02 04:26
I have unrolled the `.for`  loop in the berkeley style `Makefile`.  But for now I have not been able to test it in a linux box.  You have to wait to the evening today (europe time) so I can compile it in Linux and see if I'm able to reproduce your error.  Are you testing on master, as it has an `#ifdef HAVE_LIBUTIL_H` directive that controls if the `<libutil.h>` file (available in BSD, but not in linux) must be included.

**Comment by mojadita** [comment] 2019-10-02 04:38
For now, if you want to test it yourself, you can attach to the `I-2` branch.  If you happen to compile this source in BSD system (which requires `libutil.h` to use `forkpty(3)` function) then you need to uncomment a line in the `Makefile`.  In Linux, it should not be necessary to touch anything, but who knows, until I have a chance to test it there.

**Comment by mojadita** [comment] 2019-10-02 13:24
Now, everything has been merged into `master`.  To compile in linux, you need to modify the `Makefile` to uncomment the line
```
# CFLAGS += -DHAS_PTY_H=1
```
or make with the command:
```
make CFLAGS=-DHAS_PTY_H=1
```
while to compile in FreeBSD, you need to uncomment
```
# CFLAGS += -DHAS_LIBUTIL_H=1
```
or build the application with
```
make CFLAGS=-DHAS_LIBUTIL_H=1
```

**Closed as completed** 2019-10-02 13:25 UTC
Labels: bug
